//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class kiralik
{
    public int kiralikID { get; set; }
    public int musteriID { get; set; }
    public int filmID { get; set; }
    public System.DateTime kiraTarihi { get; set; }
    public string filmadi { get; set; }

    public virtual film film { get; set; }
    public virtual musteri musteri { get; set; }
}
